#!/bin/sh /etc/rc.common
START=98

PROG=/usr/sbin/bearDropper
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

getKids() { 
	grep -E "^PPid:\s*$1$" /proc/[0-9]*/status | cut -f3 -d/ | xargs echo
}

start() {
	echo Starting bearDropper
	service_start ${PROG} -m follow
}

stop() {
	PID=`cat /var/run/bearDropper.pid`
	echo Stopping bearDropper $PID
	kill `getKids $PID`
	sleep 1
	service_stop ${PROG}
	rm -f /tmp/bearDropper.*
}
